#!/usr/bin/env python
"""Build paper-ready BASS-GSF RankDelta table snippets from summary JSON.

The generated Markdown and LaTeX snippets are intentionally conservative:
paper rows are filled only from summary JSON backed by eval JSON and
deployment-risk summaries, and the paper-position note comes from the
closure-plan JSON.  The script never launches jobs or infers metrics from
checkpoints/logs.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


SUMMARY_JSON = Path(
    "work_dirs/semantic_scale_six_experiments_20260620/"
    "bass_rankdelta_summary.json")
CLOSURE_PLAN_JSON = Path(
    "work_dirs/semantic_scale_six_experiments_20260620/"
    "bass_rankdelta_closure_plan.json")
OUT_JSON = Path(
    "work_dirs/semantic_scale_six_experiments_20260620/"
    "bass_rankdelta_paper_snippets.json")
OUT_MD = Path(
    "resultmd/exp_p4_scale_semantic_validation/"
    "fsnippet_20260620_bass_rankdelta_paper_table.md")
OUT_TEX = Path(
    "paper/semantic_scale_support_iclr/generated/"
    "bass_rankdelta_table.tex")

TABLE_COLUMNS = [
    "method",
    "mAP",
    "AP50",
    "localized_wrong",
    "sise_logz",
    "top5000_precision",
    "top5000_sise_logz",
    "risk_weighted_logz",
    "gate",
]


def read_json(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    payload = json.loads(path.read_text(encoding="utf-8"))
    return payload if isinstance(payload, dict) else {}


def _fmt(value: Any, digits: int = 6) -> str:
    if value is None:
        return "TBD"
    if isinstance(value, float):
        return f"{value:.{digits}f}"
    return str(value)


def _metric(row: dict[str, Any], key: str) -> str:
    if key in {"mAP"}:
        return _fmt(row.get(key), 6)
    if key in {"AP50"}:
        return _fmt(row.get(key), 3)
    if key in {"top5000_precision"}:
        return _fmt(row.get(key), 4)
    if key in {"risk_weighted_logz"}:
        return _fmt(row.get(key), 4)
    return _fmt(row.get(key), 0)


def _escape_tex(text: str) -> str:
    return (
        str(text).replace("\\", r"\textbackslash{}")
        .replace("&", r"\&")
        .replace("%", r"\%")
        .replace("$", r"\$")
        .replace("#", r"\#")
        .replace("_", r"\_")
        .replace("{", r"\{")
        .replace("}", r"\}")
    )


def normalize_rows(summary: dict[str, Any]) -> list[dict[str, Any]]:
    rows = summary.get("rows", [])
    if not isinstance(rows, list):
        return []
    return [row for row in rows if isinstance(row, dict)]


def build_markdown_table(rows: list[dict[str, Any]]) -> str:
    lines = [
        "| method | mAP | AP50 | localized wrong | log-z SISE | top5000 precision | top5000 log-z SISE | risk-weighted log-z | gate |",
        "|---|---:|---:|---:|---:|---:|---:|---:|---|",
    ]
    for row in rows:
        lines.append(
            "| {method} | {mAP} | {AP50} | {localized_wrong} | "
            "{sise_logz} | {top5000_precision} | {top5000_sise_logz} | "
            "{risk_weighted_logz} | `{gate}` |".format(
                method=row.get("method", ""),
                mAP=_metric(row, "mAP"),
                AP50=_metric(row, "AP50"),
                localized_wrong=_metric(row, "localized_wrong"),
                sise_logz=_metric(row, "sise_logz"),
                top5000_precision=_metric(row, "top5000_precision"),
                top5000_sise_logz=_metric(row, "top5000_sise_logz"),
                risk_weighted_logz=_metric(row, "risk_weighted_logz"),
                gate=row.get("gate", ""),
            ))
    return "\n".join(lines)


def build_latex_table(rows: list[dict[str, Any]],
                      closure_plan: dict[str, Any],
                      rank_rows_filled: int,
                      rank_rows_total: int) -> str:
    body = []
    for row in rows:
        body.append(
            "  {method} & {mAP} & {sise} & {topk} & {risk} & {gate} \\\\".format(
                method=_escape_tex(row.get("method", "")),
                mAP=_escape_tex(_metric(row, "mAP")),
                sise=_escape_tex(_metric(row, "sise_logz")),
                topk=_escape_tex(_metric(row, "top5000_precision")),
                risk=_escape_tex(_metric(row, "risk_weighted_logz")),
                gate=_escape_tex(row.get("gate", "")),
            ))
    action = _escape_tex(closure_plan.get("action", "missing"))
    position = _escape_tex(closure_plan.get("paper_position", ""))
    if rank_rows_total and rank_rows_filled == rank_rows_total:
        row_status = (
            "All RankDelta/P2 rows are filled from eval JSON plus "
            "deployment-risk summaries.")
    else:
        row_status = "Missing rows remain TBD."
    row_status = _escape_tex(row_status)
    return "\n".join([
        "% Generated by M_Tools/analysis/build_bass_rankdelta_paper_snippets.py",
        "% Do not edit metrics by hand; regenerate from summary JSON.",
        "\\begin{table}[h]",
        "\\centering",
        "\\small",
        "\\begin{tabular}{lrrrrl}",
        "\\toprule",
        "Method & mAP & log-z SISE & Top5000 Prec. & Risk-log-z & Gate \\\\",
        "\\midrule",
        *body,
        "\\bottomrule",
        "\\end{tabular}",
        "\\caption{BASS-GSF RankDelta closure table generated from existing eval JSON and deployment-risk summaries. "
        f"Closure action: {action}. Paper position: {position}. {row_status}}}",
        "\\end{table}",
        "",
    ])


def build_payload(summary: dict[str, Any],
                  closure_plan: dict[str, Any]) -> dict[str, Any]:
    rows = normalize_rows(summary)
    rank_rows = [
        row for row in rows
        if str(row.get("kind", "")).startswith("rankdelta")
    ]
    filled_rank_rows = [
        row for row in rank_rows
        if row.get("mAP") is not None and row.get("gate") != "waiting/missing"
    ]
    return {
        "summary_status": summary.get("status", "missing"),
        "closure_action": closure_plan.get("action", "missing"),
        "paper_position": closure_plan.get("paper_position", ""),
        "rankdelta_rows_total": len(rank_rows),
        "rankdelta_rows_filled": len(filled_rank_rows),
        "has_strict_pass": any(
            row.get("gate") == "strict pass" for row in rank_rows),
        "has_pilot_pass": any(
            row.get("gate") == "pilot pass" for row in rank_rows),
        "markdown_table": build_markdown_table(rows),
        "latex_table": build_latex_table(
            rows, closure_plan, len(filled_rank_rows), len(rank_rows)),
        "no_fabrication_rule": (
            "Rows are filled only from eval JSON and deployment-risk summary "
            "JSON already present in bass_rankdelta_summary.json."),
    }


def write_outputs(payload: dict[str, Any], out_json: Path, out_md: Path,
                  out_tex: Path) -> None:
    out_json.parent.mkdir(parents=True, exist_ok=True)
    out_json.write_text(
        json.dumps({
            key: value
            for key, value in payload.items()
            if key not in {"markdown_table", "latex_table"}
        }, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8")

    md_lines = [
        "# BASS-GSF RankDelta Paper Table Snippet - 2026-06-20",
        "",
        "Generated from `bass_rankdelta_summary.json` and "
        "`bass_rankdelta_closure_plan.json`. It does not launch experiments or "
        "infer missing metrics.",
        "",
        "| field | value |",
        "|---|---|",
        f"| summary_status | `{payload['summary_status']}` |",
        f"| closure_action | `{payload['closure_action']}` |",
        f"| paper_position | {payload['paper_position']} |",
        f"| rankdelta_rows_filled | `{payload['rankdelta_rows_filled']}/{payload['rankdelta_rows_total']}` |",
        f"| has_strict_pass | `{payload['has_strict_pass']}` |",
        f"| has_pilot_pass | `{payload['has_pilot_pass']}` |",
        "",
        "## Markdown Table",
        "",
        payload["markdown_table"],
        "",
        "## No-Fabrication Rule",
        "",
        payload["no_fabrication_rule"],
        "",
        "## LaTeX Snippet",
        "",
        f"`{out_tex}`",
        "",
    ]
    out_md.parent.mkdir(parents=True, exist_ok=True)
    out_md.write_text("\n".join(md_lines), encoding="utf-8")

    out_tex.parent.mkdir(parents=True, exist_ok=True)
    out_tex.write_text(payload["latex_table"], encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--summary-json", default=str(SUMMARY_JSON))
    parser.add_argument("--closure-plan-json", default=str(CLOSURE_PLAN_JSON))
    parser.add_argument("--out-json", default=str(OUT_JSON))
    parser.add_argument("--out-md", default=str(OUT_MD))
    parser.add_argument("--out-tex", default=str(OUT_TEX))
    args = parser.parse_args()

    payload = build_payload(
        read_json(Path(args.summary_json)),
        read_json(Path(args.closure_plan_json)))
    write_outputs(
        payload, Path(args.out_json), Path(args.out_md), Path(args.out_tex))
    print(json.dumps({
        "summary_status": payload["summary_status"],
        "closure_action": payload["closure_action"],
        "rankdelta_rows_filled": payload["rankdelta_rows_filled"],
        "rankdelta_rows_total": payload["rankdelta_rows_total"],
        "out_json": args.out_json,
        "out_md": args.out_md,
        "out_tex": args.out_tex,
    }, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
