#!/usr/bin/env python
"""Merge angle-sweep predictions into a requested target-angle pose."""

import argparse
import pickle
from collections import defaultdict
from pathlib import Path

import cv2
import numpy as np
import torch

from openrsd_env import preload_installed_mmengine

preload_installed_mmengine()

from mmcv.ops import box_iou_rotated, nms_rotated

from mmrotate.structures.bbox import qbox2rbox, rbox2qbox


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('--prediction', action='append', required=True)
    parser.add_argument('--angle', action='append', type=float, required=True)
    parser.add_argument(
        '--target-angle',
        type=float,
        default=0.0,
        help='Target coordinate angle. 0 keeps the original canonical pose.')
    parser.add_argument('--out', required=True)
    parser.add_argument('--img-shape', nargs=2, type=int, default=[1024, 1024])
    parser.add_argument('--score-thr', type=float, default=0.05)
    parser.add_argument('--pre-nms-topk', type=int, default=4000)
    parser.add_argument('--nms-iou', type=float, default=0.1)
    parser.add_argument('--max-per-img', type=int, default=2000)
    parser.add_argument('--score-rule', choices=['max', 'mean'], default='max')
    return parser.parse_args()


def canonical_img_id(img_id):
    if isinstance(img_id, (int, np.integer)):
        img_id = str(img_id)
    if img_id.startswith('angle_') and '__' in img_id:
        return img_id.split('__', 1)[1]
    return img_id


def rotation_matrix(width, height, angle):
    center = ((width - 1) / 2.0, (height - 1) / 2.0)
    return cv2.getRotationMatrix2D(center, float(angle), 1.0)


def transform_qboxes(qboxes, matrix):
    if qboxes.size == 0:
        return qboxes
    points = qboxes.reshape(-1, 2).astype(np.float32)
    hom = np.concatenate(
        [points, np.ones((points.shape[0], 1), dtype=np.float32)], axis=1)
    transformed = hom @ matrix.T
    return transformed.reshape(-1, 8).astype(np.float32)


def tensor_to_numpy(value):
    if hasattr(value, 'detach'):
        return value.detach().cpu().numpy()
    return np.asarray(value)


def load_predictions(path):
    with open(path, 'rb') as f:
        return pickle.load(f)


def transform_boxes_to_target(rboxes, source_angle, target_angle, width,
                              height):
    if len(rboxes) == 0:
        return np.zeros((0, 5), dtype=np.float32)
    qboxes = rbox2qbox(torch.from_numpy(rboxes.astype(np.float32))).numpy()
    # Datasets are generated by rotating the same 1024x1024 patch around the
    # same center, so view -> target is a single affine rotation by
    # (target - source).  For target=0 this is the old inverse-to-canonical path.
    matrix = rotation_matrix(width, height, target_angle - source_angle)
    target_qboxes = transform_qboxes(qboxes, matrix)
    return qbox2rbox(torch.from_numpy(target_qboxes)).numpy().astype(np.float32)


def merge_one_image(items, score_thr, pre_nms_topk, nms_iou, max_per_img,
                    score_rule='max'):
    if not items:
        return {
            'bboxes': torch.zeros((0, 5), dtype=torch.float32),
            'labels': torch.zeros((0, ), dtype=torch.long),
            'scores': torch.zeros((0, ), dtype=torch.float32),
        }

    boxes = np.concatenate([item['bboxes'] for item in items], axis=0)
    labels = np.concatenate([item['labels'] for item in items], axis=0)
    scores = np.concatenate([item['scores'] for item in items], axis=0)
    keep = scores >= score_thr
    boxes, labels, scores = boxes[keep], labels[keep], scores[keep]
    if pre_nms_topk > 0 and len(scores) > pre_nms_topk:
        order = np.argsort(-scores)[:pre_nms_topk]
        boxes, labels, scores = boxes[order], labels[order], scores[order]

    out_boxes = []
    out_labels = []
    out_scores = []
    for label in sorted(set(labels.tolist())):
        inds = np.where(labels == label)[0]
        if len(inds) == 0:
            continue
        label_boxes = torch.from_numpy(boxes[inds].astype(np.float32))
        label_scores = torch.from_numpy(scores[inds].astype(np.float32))
        nms_dets, keep_inds = nms_rotated(label_boxes, label_scores, nms_iou)
        if score_rule == 'max':
            final_boxes = nms_dets[:, :5]
            final_scores = nms_dets[:, 5]
        else:
            keep_boxes = nms_dets[:, :5]
            ious = box_iou_rotated(label_boxes, keep_boxes).cpu().numpy()
            assigned = np.full(len(label_boxes), False, dtype=bool)
            final_boxes = []
            final_scores = []
            for keep_idx in range(len(keep_boxes)):
                cluster = np.where((ious[:, keep_idx] >= nms_iou) & (~assigned))[0]
                if len(cluster) == 0:
                    cluster = np.array([int(keep_inds[keep_idx])], dtype=np.int64)
                assigned[cluster] = True
                final_boxes.append(keep_boxes[keep_idx])
                final_scores.append(float(label_scores[cluster].mean().item()))
            final_boxes = torch.stack(final_boxes, dim=0)
            final_scores = torch.tensor(final_scores, dtype=torch.float32)
        out_boxes.append(final_boxes)
        out_scores.append(final_scores)
        out_labels.append(
            torch.full((len(final_scores), ), int(label), dtype=torch.long))

    if not out_boxes:
        return {
            'bboxes': torch.zeros((0, 5), dtype=torch.float32),
            'labels': torch.zeros((0, ), dtype=torch.long),
            'scores': torch.zeros((0, ), dtype=torch.float32),
        }

    boxes_t = torch.cat(out_boxes, dim=0)
    labels_t = torch.cat(out_labels, dim=0)
    scores_t = torch.cat(out_scores, dim=0)
    order = torch.argsort(scores_t, descending=True)
    if max_per_img > 0:
        order = order[:max_per_img]
    return {
        'bboxes': boxes_t[order].contiguous(),
        'labels': labels_t[order].contiguous(),
        'scores': scores_t[order].contiguous(),
    }


def main():
    args = parse_args()
    if len(args.prediction) != len(args.angle):
        raise ValueError('--prediction and --angle must have the same count')

    height, width = args.img_shape
    grouped = defaultdict(list)
    metadata = {}
    for pred_path, angle in zip(args.prediction, args.angle):
        for sample in load_predictions(pred_path):
            img_id = canonical_img_id(sample['img_id'])
            pred = sample['pred_instances']
            boxes = tensor_to_numpy(pred['bboxes']).astype(np.float32)
            labels = tensor_to_numpy(pred['labels']).astype(np.int64)
            scores = tensor_to_numpy(pred['scores']).astype(np.float32)
            inv_boxes = transform_boxes_to_target(boxes, angle,
                                                  args.target_angle, width,
                                                  height)
            grouped[img_id].append(
                dict(bboxes=inv_boxes, labels=labels, scores=scores))
            metadata.setdefault(img_id, sample)

    merged = []
    for img_id in sorted(grouped):
        sample = dict(metadata[img_id])
        sample['img_id'] = img_id
        sample['pred_instances'] = merge_one_image(grouped[img_id],
                                                   args.score_thr,
                                                   args.pre_nms_topk,
                                                   args.nms_iou,
                                                   args.max_per_img,
                                                   args.score_rule)
        merged.append(sample)

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open('wb') as f:
        pickle.dump(merged, f)
    print(
        f'Wrote {out_path} images={len(merged)} target_angle={args.target_angle}'
    )


if __name__ == '__main__':
    main()
